from building import *
import rtconfig

if GetDepend('_SIMPLIFIED_AT_'):
    src = []
    CPPPATH = []
else:
    cwd = GetCurrentDir()
    src = Glob('*.c')
    CPPPATH = [cwd]

group = DefineGroup('quick', src, depend = ['_QUICK_CONNECT_'], CPPPATH = CPPPATH)

Return('group')
