Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Glob('*.c')
path = [cwd]

group = DefineGroup('HAL_Drivers', src, depend = [''], CPPPATH = path)

Return('group')
