Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Glob('src/*.c')
path = [cwd + '/inc']

group = DefineGroup('UC8288_HAL_Driver', src, depend = [''], CPPPATH = path)

Return('group')
