# for module compiling
import os
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()

path = [cwd + '/app/include']
path += [cwd + '/app/test']
path += [cwd + '/at_simplified/']
path += [cwd + '/at/']

src = Glob('app/test/*.c')
src += Glob('app/src/*.c')

if GetDepend('_SIMPLIFIED_AT_'):
    src += Glob('at_simplified/*.c')
    src += Glob('at/ati_prs.c')
else:
    src += Glob('at/*.c')


lib = ['libwin_wiota_dev_v4.4']
libpath = [cwd + '/lib']

group = DefineGroup('PS', src, depend = [''], CPPPATH = path, LIBS = lib, LIBPATH = libpath)

Return('group')
