# for module compiling
import os
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()

path = [cwd + '/app/include']
path += [cwd + '/app/test']
path += [cwd + '/at']

src = Glob('app/test/*.c')
src += Glob('app/src/*.c')
src += Glob('at/*.c')

if GetDepend(['WIOTA_ASYNC_GATEWAY_API']):
    path += [cwd + '/app/coding']
    path += [cwd + '/app/fastlz']
    src += Glob('app/coding/*.c')
    src += Glob('app/fastlz/*.c')

lib = ['libwin_wiota_dev']
libpath = [cwd + '/lib']

group = DefineGroup('PS', src, depend = [''], CPPPATH = path, LIBS = lib, LIBPATH = libpath)

Return('group')
