
from building import *
import rtconfig

cwd     = GetCurrentDir()

src =  Glob('*.c')
CPPPATH = [cwd]

LOCAL_CCFLAGS = ''

group = DefineGroup('efuse_drv', src, depend = [''], CPPPATH = CPPPATH, LOCAL_CCFLAGS = LOCAL_CCFLAGS)\

Return('group')
